apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: thomasrannouwebapphelloaks 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: thomasrannouwebapphelloaks 
    spec:
      containers:
        - name: thomasrannouwebapphelloaks 
          image: acr2003.azurecr.io/thomasrannouwebapphelloaks
          ports:
          - containerPort: 80